### ISSUE TITLE
Request: SDK icon

### ISSUE THREAD

**Issue by ShaunLynch** [carbon-design-system/carbon-icons#108]
#### 1. Team name

IBM Blockchain Platform

#### 2. Icon name

SDK

#### 3. Please briefly describe what the icon is supposed to represent and the use case(s) its being used for.

We need an icon to signify SDKs for fabric development so users will be able to quickly and succintly identify what they can expect at a glance.

I would create this myself if I had the building blocks for the type.

#### 5. Screen Shot

Example of something similar

<img width="2209" alt="image" src="https://user-images.githubusercontent.com/35451841/62459621-cb38cf80-b777-11e9-8385-2d12241faccd.png">

**Comment by shixiedesign** [comment]
Hi @ShaunLynch, here's the guidance for creating and contributing an icon. Let us know if you'd need additional help with it. Usually I go into Illustrator to create the 32x32px artboard and start from there. Thanks! https://www.ibm.com/design/language/elements/icons/contribute/

**Comment by ShaunLynch** [comment]
Hey @shixiedesign is there a document containing the building blocks for these type icons? Just curious if there's an alphabet of this particular type style where I can fit my own together.

I see that the ascenders/descenders are all 2px rectangles however the corners and diagonal pieces aren't as straightforward. I'm concerned about the 'S' and 'K' specifically.

If not I can take a swing at it and give it my best shot

**Comment by shixiedesign** [comment]
Lemme check for ya - one sec

**Comment by shixiedesign** [comment]
You probably can take the S from SVG, K from 4K etc. 

![image](https://user-images.githubusercontent.com/15144993/62553545-27155e00-b835-11e9-8fab-e377256b1ef4.png)

This [AI file](https://ibm.box.com/s/ofxse1smwd8hw10shtor61z0qg8p8gx2) (page 5) has everything you need I believe: 
![image](https://user-images.githubusercontent.com/15144993/62553721-7a87ac00-b835-11e9-8a79-39d800c4adeb.png)

Here's the link to view all our icons in the icon-package: 
https://carbon-elements.netlify.com/icons/examples/preview/#32%2F4K

If you need the grid, our icons are drawn on the same grid as App icon grid https://github.ibm.com/carbon/app-icons/

👍 you good?

**Comment by ShaunLynch** [comment]
@shixiedesign That document was perfect for what I needed thank you. Here's the 'SDK' icon at all the appropriate sizes below. ✌️ 

[SDK icons.zip](https://github.com/carbon-design-system/carbon-icons/files/3476218/SDK.icons.zip)

<img width="1900" alt="image" src="https://user-images.githubusercontent.com/35451841/62610494-b4bb8100-b8fb-11e9-8138-9bf343e78370.png">

**Comment by conradennis** [comment]
@ShaunLynch looks good to me! @shixiedesign you want me to handle adding this one or do you got it?

**Comment by shixiedesign** [comment]
@conradennis would be awesome if you can take it!! Thanks!

**Comment by mjabbink** [comment]
@conradennis did this get added?

**Comment by mjabbink** [comment]
I see it is. Great!

**Comment by mjabbink** [comment]
We should close issue

**Comment by mjabbink** [comment]
@conradennis Close
