### ISSUE TITLE
Contribution: City Icon Hamburg

### ISSUE THREAD

**Issue by fabianklonsdorf** [carbon-design-system/carbon-icons#115]
#### 1. Team name
IBM Studios Hamburg

#### 2. Icon name
City Icons / Hamburg

#### 3. Please briefly describe what the icon is supposed to represent and the use case(s) its being used for.
The city icon is derived from the blazon of Hamburg. As Hamburg is a major location in IBM DACH and an IBM Garage location, we as IBM Studios Hamburg firmly believe, that a dedicated icon is needed.

#### 4. Box Link

https://ibm.box.com/s/jlpxk38swf80cu88z6uot4l82gynpw6j

#### 5. Screen Shot

1.  Close-up screen shot of the icon with the pixel grid turned on
<img width="788" alt="Screenshot 2019-12-07 at 01 36 21" src="https://user-images.githubusercontent.com/47037236/70365714-1d5b4000-1893-11ea-9ccb-68aad04bf14e.png">

**Comment by mjabbink** [comment]
@conradennis can you create this issue in Pictogram repo.

**Comment by mjabbink** [comment]
Maybe a pictogram more literal to flag and coat of arms?

![41AB03A7-D27F-4A01-AE40-01B1BDAA5776](https://user-images.githubusercontent.com/32881239/72688887-56611400-3ad1-11ea-9da6-f29369526ada.jpeg)

**Comment by mjabbink** [comment]
![6724322D-F839-484F-82B9-F52B8B372A32](https://user-images.githubusercontent.com/32881239/72689257-3b909e80-3ad5-11ea-94db-a839b0e271d3.jpeg)

**Comment by mjabbink** [comment]
This can be close
