### ISSUE TITLE
Please consider merging carbon-icons with ibm-design-language-icons

### ISSUE THREAD

**Issue by gmosx** [carbon-design-system/carbon-icons#12]
Both are open-source and very similar.
It would be better to have one combined icon library.

**Comment by hellobrian** [comment]
Maybe someday. I do agree that both are similar but we curated carbon-icons to be specific to the majority of our users in IBM Cloud.

I think there are a lot of great things about carbon-icons that can be used in the IBM Design Language (IDL) icon library to make it a more developer-friendly asset library.

But for right now, this is not something we're pursuing.

With carbon-design-system as a whole, carbon-icons originated to be used by products under the IBM Cloud organization (Bluemix, Watson, etc.). IBM Cloud is our primary and majority user-base.

Before carbon-design-system, we were using IDL icons directly and it wasn't the ideal usage for our IBM Cloud teams. So we created carbon-icons which add the subset of IDL icons we actually use and includes our own icons that were used uniquely within products like Bluemix.
