### ISSUE TITLE
iconFolderAdd is missing, same as iconFolder

### ISSUE THREAD

**Issue by ljitendra** [carbon-design-system/carbon-icons#123]
#### 3. Please briefly describe what the icon is supposed to represent and the use case(s) its being used for.
Based on documentation site, 'folder' and 'folder add' are two different icons. But 'folder add' icon is missing and it is the same as 'folder' icon.

#### 5. Screen Shot

<img width="458" alt="Screen Shot 2020-03-18 at 9 38 48 AM" src="https://user-images.githubusercontent.com/15458935/76966401-49f40e80-68fc-11ea-80a9-c95da2fbb8df.png">

**Comment by joshblack** [comment]
Hi there @ljitendra! 👋 This project will be deprecated in the upcoming months and has been replaced by the following:

- [Vanilla](https://github.com/carbon-design-system/carbon/tree/master/packages/icons)
- [React](https://github.com/carbon-design-system/carbon/tree/master/packages/icons-react)

All assets available on the website are made available through these packages. Hope this helps!
