### ISSUE TITLE
Unable to find AnalyticsReference icon in version 7

### ISSUE THREAD

**Issue by shubh1608** [carbon-design-system/carbon-icons#132]
#### 3. I am using carbon-icons version "^7.0.7"

Please guide me on using it in the carbon-icon version 7

**Comment by joshblack** [comment]
Hi there @shubh1608! 👋 

The `carbon-icons` package is unfortunately in maintenance mode, newer icons will be available in `@carbon/icons` and `@carbon/icons-react`. Hope this helps!
