### ISSUE TITLE
Do not suggest app.use(express.static('node_modules')

### ISSUE THREAD

**Issue by alon24** [carbon-design-system/carbon-icons#24]
in the readme and in the actual code (server.js) it says:
app.use(express.static('node_modules'));

this should not be suggested or used, it should be:
1. add task to copy icon file to public/svg
2. use that file from public/svg

**Comment by hellobrian** [comment]
Thanks for pointing this out, and sorry if this caused any issues - I'm updating the docs now with your recommendation.

**Comment by hellobrian** [comment]
Also, feel free to leave comments on the PR that's up: https://github.com/carbon-design-system/carbon-icons/pull/25 , if there's anything else I should change I'd be happy to hear more of your feedback.
