### ISSUE TITLE
New Icon for OpenWhisk

### ISSUE THREAD

**Issue by yumeforever** [carbon-design-system/carbon-icons#36]
As we are moving forward with rebranding of OpenWhisk we will need a different icon for it on Bluemix menu:
<img width="251" alt="screen shot 2017-08-08 at 09 38 38" src="https://user-images.githubusercontent.com/3612533/29074750-ae20cd94-7c50-11e7-91ee-f82c65e16dc1.png">

The idea is to replace with this one:
<img width="241" alt="screen shot 2017-08-08 at 15 44 14" src="https://user-images.githubusercontent.com/3612533/29074761-b922f816-7c50-11e7-82ad-f0dd5f364525.png">

Is it ok? Should I made changes?
Can I send the SVG?

**Comment by hellobrian** [comment]
Yes, can you copy and paste the SVG code here in the issue? 

1. Locate your SVG file in Finder 
2. Open SVG file with sketch
3. Right-click > Copy SVG Code

**Comment by dallashudgens** [comment]
@yumeforever When is the name changing? Because we have to change that in abstraction layer as well (for the left navigation and the catalog. We'll probably want to make sure those both change at the same time

**Comment by hellobrian** [comment]
The name shouldn't matter if you start using the inline SVG. We're trying to pull away from relying on `<use xlink:href>`. We'll probably name the new icon as `open-whisk-v2` or something for the purposes of searching on the carbon website and deprecating the old whisk icon.

**Comment by dallashudgens** [comment]
Sorry, I didn't mean the name of the svg, I mean the actual name of the OpenWhisk service. The name is Changing to Functions, so I need to update that in the Global Left Navigation

**Comment by yumeforever** [comment]
I will double check this today! 
As far as I read yesterday night, we got clearance for changing. 
Brb today with updates ;) thanks both!

**Comment by yumeforever** [comment]
Done! Here it is the SVG


<svg width="25px" height="25px" viewBox="0 0 25 25" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    
    <desc>Created with Sketch.</desc>
    <defs></defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="Group" transform="translate(1.000000, 1.000000)" stroke="#000000">
            <g id="Group-14-Copy">
                <path d="M13.2669399,22.4782451 C15.4932917,22.1004832 17.6270147,21.0651927 19.3463781,19.34645 C23.6157581,15.0777634 23.7668941,8.24971989 19.7997861,3.79918576" id="Fill-1" stroke-linecap="round"></path>
                <path d="M9.53427094,0.165212592 C7.25910058,0.524036601 5.07279716,1.56606731 3.31940313,3.31882812 C-0.949756131,7.58868065 -1.10109718,14.4156194 2.86537998,18.8654786" id="Fill-4" stroke-linecap="round"></path>
                <path d="M8.32761895,11.1651321 C8.3261098,11.2315684 8.32530223,11.2987594 8.326,11.3676063 L8.326,11.604075 C8.3216875,17.6696063 8.08378125,21.3546375 4.82209375,21.3984813 C4.50584375,21.4027938 4.38365625,21.649325 4.361375,21.9634188 C4.3398125,22.2796688 4.424625,22.5592625 4.73728125,22.6074188 C4.78184375,22.6146063 5.13403125,22.6656375 5.6795625,22.6656375 C6.92515625,22.6656375 9.17915625,22.3982625 11.0996563,20.7300438 C13.308375,18.8095438 14.398,15.6355438 14.3405,11.3007625 L14.3405,11.0989886 L17.1024249,10.5079347 C17.5348993,10.419331 17.5551882,10.0681974 17.5530525,9.63064786 C17.5519847,9.19419216 17.5263566,8.84634025 17.0938822,8.76101809 L14.3773404,8.20859156 C14.5120122,3.86359945 15.131488,1.30400552 17.8436875,1.26773125 C18.1592188,1.26341875 18.1994688,1.0168875 18.2224688,0.702075 C18.2440313,0.38654375 18.2404375,0.10695 17.9277813,0.05879375 C17.8846563,0.05160625 17.5324688,-0.00014375 16.9869375,-0.00014375 C15.7420625,-0.00014375 13.486625,0.26723125 11.5668438,1.93473125 C9.96106278,3.33138725 8.95307144,5.39895308 8.54165791,8.09077348 L5.25459934,8.7774262 C4.82212497,8.86493611 4.79863254,9.21278802 4.79863254,9.65143146 C4.79863254,10.0878872 4.82212497,10.4368329 5.25459934,10.5243429 L8.32761935,11.1651321 Z" id="Combined-Shape"></path>
            </g>
        </g>
    </g>
</svg>

**Comment by yumeforever** [comment]
Hey, just to mentioned, the name should be changed to "Functions" too :)

**Comment by hellobrian** [comment]
I'll get this merged today and hopefully on the website today. 

Just needed to point out that next time there's one thing you can do when exporting new SVG icons (step 3 for Adobe and Sketch):

![image](https://user-images.githubusercontent.com/4185382/29221800-b17d5868-7e85-11e7-8b87-bb66a58d133a.png)

![image](https://user-images.githubusercontent.com/4185382/29221855-ed44cfc0-7e85-11e7-8e73-77161d00212c.png)

Doing this allows us to change the `fill` color of this pictogram so that it just fills the outlines of the shapes.

**Comment by aliciahickman** [comment]
Hi! I am making this icon change to the nav in Common, will be submitting this PR today: 
![image](https://user-images.githubusercontent.com/4836277/29223055-be756a56-7e8a-11e7-9c6d-3c01b8cc7c3c.png)

**Comment by hellobrian** [comment]
Here's the SVGO optimized version of `functions.svg` to use in production @aliciahickman 

```xml
<svg width='25' height='25' viewBox='0 0 25 25' fill-rule='evenodd'>
  <path d='M14.3 24c-.2 0-.5-.2-.5-.4 0-.3.1-.5.4-.6 2.2-.4 4.2-1.4 5.8-3 4.1-4.1 4.2-10.6.4-14.9-.2-.2-.2-.5 0-.7.2-.2.5-.2.7 0 4.2 4.7 4 11.8-.5 16.2-1.6 1.8-3.8 3-6.3 3.4zM3.9 20.4c-.1 0-.3-.1-.4-.2C-.7 15.5-.5 8.4 4 4 5.8 2.2 8 1.1 10.5.7c.3 0 .5.1.6.4 0 .3-.1.5-.4.6-2.3.4-4.3 1.4-5.9 3-4.2 4-4.4 10.6-.6 14.8.2.2.2.5 0 .7-.1.1-.2.2-.3.2z'></path>
  <path d='M6.7 24.2c-.6 0-.9-.1-1-.1-.4-.1-.9-.4-.8-1.2.1-.8.5-1 1-1 2.6 0 3-2.8 3-9.3L6.2 12c-.9-.2-.9-1-.9-1.3 0-.4 0-1.2.9-1.4l2.9-.6C9.6 6 10.6 4 12.2 2.6 14.3.8 16.7.5 17.9.5c.6 0 1 .1 1 .1.5.1.8.5.7 1.2 0 .3-.1 1-.9 1-2 0-2.8 1.6-3 6l2.3.5c.9.2.9 1 .9 1.4 0 .4 0 1.2-.9 1.4l-2.4.5c0 4.4-1.1 7.6-3.4 9.6-1.8 1.7-4.3 2-5.5 2zM6 23.1c.5 0 3.4.3 5.8-1.8 2.1-1.8 3.1-4.9 3.1-9v-.6L18 11c.1-.1.1-.3.1-.4v-.4l-3.2-.6v-.4c.1-3.7.5-7.3 3.8-7.4v-.2H18c-1.1 0-3.3.2-5.1 1.8-1.5 1.3-2.5 3.3-2.9 5.9v.2l-3.6.8c-.1 0-.1.3-.1.4v.4l3.5.7v.8c0 5.2 0 10.2-4 10.3v.1c.1.1.1.1.2.1-.1 0-.1 0 0 0z'></path>
</svg>
```

**Comment by hellobrian** [comment]
Merged: https://github.com/carbon-design-system/carbon-icons/pull/37
