### ISSUE TITLE
Add Header icons to carbon-icons

### ISSUE THREAD

**Issue by bsonefeld** [carbon-design-system/carbon-icons#39]

**Comment by bsonefeld** [comment]
Yeah I was referring to the L0 icons, did those get added to our icon library?

**Comment by aagonzales** [comment]
Nope, L0 ones aren't in the library. Looks like they're in here: https://ibm.box.com/s/w7n0w1ifuynlss7b5hg5y7ofqo4h42yk

- there's a competing avatar (carbon-icons has one but its different)
- so the only the bell notification and the 6 dot one needs to be added.

Can you think of any others?

**Comment by bsonefeld** [comment]
Do we have the proper hamburger menu icon in our library? (the one that's being used in the L0)

**Comment by joshblack** [comment]
Closing in favor of: https://ibm.biz/BdZgju
