### ISSUE TITLE
Not able to download icons using Firefox

### ISSUE THREAD

**Issue by marijohannessen** [carbon-design-system/carbon-icons#54]
![screen shot 2018-01-22 at 10 42 19 am](https://user-images.githubusercontent.com/5447411/35232384-f15c4bfe-ff60-11e7-8a73-28b3b663509e.png)

This error message shows up when trying to download an icon from Firefox. We need to make sure that the SVG's include namespaces:

> Make sure you always declare the namespaces you use in your XML files. If you don't, user agents such as Firefox won't recognize your content and will simply show the XML markup or inform the user that there's an error in the XML. . . .

More info: https://developer.mozilla.org/en-US/docs/Web/SVG/Namespaces_Crash_Course

**Comment by joshblack** [comment]
Hey @marijohannessen! Having a hard time reproducing this on Firefox ESR. Was this tied to a specific version of FF? I might also be missing how to reproduce, so let me know! 🙂
