### ISSUE TITLE
Latest version of carbon-icons contains es6 code

### ISSUE THREAD

**Issue by johannott** [carbon-design-system/carbon-icons#57]
I have a project that has a dependancy on carbon-icons version 6.3.0. 

There is a file called `carbon-icons-list.js` in the dist folder that contains ES6 code and is currently breaking the pipeline of my project. 

```lerna ERR!   SyntaxError: Unexpected token 'const'
lerna ERR!   at /node_modules/carbon-icons/dist/carbon-icons-list.js:1:0
lerna ERR!

**Comment by asudoh** [comment]
Fixed by: https://github.com/carbon-design-system/carbon-icons/pull/58 - Sorry for the inconveniences that causes!
