### ISSUE TITLE
Some 9.0.0 icons are missing the 45 degree inside corner

### ISSUE THREAD

**Issue by jackiwakin** [carbon-design-system/carbon-icons#71]
## Detailed description

> Describe in detail the issue you're having.

It would appear a few of the icons missed the 45 degree inside corners

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug

> What version of the Carbon Design System are you using?

9.0.0

## Additional information
<img width="341" alt="screen shot 2018-06-06 at 11 11 47 am" src="https://user-images.githubusercontent.com/39998794/41048134-1255ee52-697c-11e8-8e1a-5177586b376f.png">
<img width="409" alt="screen shot 2018-06-06 at 11 12 06 am" src="https://user-images.githubusercontent.com/39998794/41048135-1262307c-697c-11e8-8d56-dc04624c56b3.png">
<img width="243" alt="screen shot 2018-06-06 at 11 12 50 am" src="https://user-images.githubusercontent.com/39998794/41048136-1272e2b4-697c-11e8-92eb-9ad15c3796ff.png">
<img width="154" alt="screen shot 2018-06-06 at 11 14 13 am" src="https://user-images.githubusercontent.com/39998794/41048137-1289c51a-697c-11e8-835f-954c59a7aa34.png">

**Comment by joshblack** [comment]
cc @tay-aitken just to confirm if this is in the Sketch file, or not. Could easily be a mistake in our build step.

Also, just a heads up @jackiwakin make sure not to make any public references to that one project 👍

**Comment by tay-aitken** [comment]
Hi @jackiwakin! Thanks for bringing this to our attention. These have now been fixed. They will be updated in the next kit release in the design kit/library (which currently does not have an expected/planned release date) . @joshblack it it a breaking change to update these icons in the repo?

**Comment by tay-aitken** [comment]
Just a note: will not be updating the `forum` icon to have those corners as the library we inherited from does not follow that styling on that particular icon.

**Comment by tay-aitken** [comment]
Going to close this issue as the icons with the error have been fixed :)

**Comment by tay-aitken** [comment]
This was addressed in PR #76
