### ISSUE TITLE
icons have centered single px stroke

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon-icons#72]
## Detailed description

> icon--back-to-top, icon--download have centered single px stroke; icon--back-to-top cropped artboard is 11px, but will still be placed in 16px wide and will still straddle a px border. icon--download has a border straddling 1px stroke in prod. there may be others.

> Bug

![image](https://user-images.githubusercontent.com/35537391/41619162-37b9a222-73d3-11e8-9b89-10f41909ac66.png)

**Comment by tay-aitken** [comment]
Chris I am closing this as the image above was one of the old icons that have been removed.
