### ISSUE TITLE
Logging and Monitoring Icon for Hamburger Menu

### ISSUE THREAD

**Issue by SpencerReynolds18** [carbon-design-system/carbon-icons#74]
Creating an icon for the new "Logging and Monitoring" section in the Hamburger menu. 
![image 1 1](https://user-images.githubusercontent.com/19826147/41682568-b0f1f3e0-749d-11e8-80cb-99bfef919fa0.png)

Here is the SVG designed and exported on the pixel grid. Let me know if you need anything else.
@tay-aitken 

[Logging and Monitoring Icon.svg.zip](https://github.com/carbon-design-system/carbon-icons/files/2120920/Logging.and.Monitoring.Icon.svg.zip)

**Comment by tay-aitken** [comment]
@SpencerReynolds18 great job aligning to the pixel grid! The only thing I would suggest is maybe working on the data line a bit. Maybe getting rid of that last bump in data. It isn't translating well in pixel format. I would recommend making the line an N shape I think that will help with icon clarity.
<img width="632" alt="screen shot 2018-06-20 at 3 36 17 pm" src="https://user-images.githubusercontent.com/29312997/41683320-e19b1efc-749f-11e8-843f-b05f5212b029.png">

**Comment by chrisconnors-ibm** [comment]
@SpencerReynolds18 Are you still waiting on this?

**Comment by SpencerReynolds18** [comment]
Sorry, I don't check my non enterprise account much, I will sync up with Diana Sun on this and take another pass to clean it up.

**Comment by SpencerReynolds18** [comment]
[Logging and Monitoring Icon_Logging and Monitoring Icon.svg.zip](https://github.com/IBM/carbon-icons/files/2456893/Logging.and.Monitoring.Icon_Logging.and.Monitoring.Icon.svg.zip)
Updated according to Tayler's feedback. Let me know if y'all need anything else. Thanks!

**Comment by chrisconnors-ibm** [comment]
@SpencerReynolds18 is this still seeking approval since June?

**Comment by conradennis** [comment]
Versions of these icons that are compatible with the new IBM Design Language are available here: https://next.carbondesignsystem.com/guidelines/iconography/library in the sketch kit or as individual SVGs from the icon library

**Comment by mjabbink** [comment]
@conradennis close?

**Comment by mjabbink** [comment]
@conradennis Close.
