### ISSUE TITLE
Travis: check-in build files

### ISSUE THREAD

**Issue by hellobrian** [carbon-design-system/carbon-icons#8]
- [X] Needed for CI
- [X] Tests 
- [ ] check-in build files,
- [X] npm publish

**Comment by hellobrian** [comment]
Npm publish is done. Need more time to figure out check-in for build files. For now, all pull requests can do npm run build

**Comment by aagonzales** [comment]
Not a priority but @joshblack could you check this out when you get a chance? Not sure if this has been resolved already.

**Comment by joshblack** [comment]
@aagonzales yeah for sure! Could you help fill me in on context for this? Might also be worth talking about the icon authoring flow you had mentioned earlier.

**Comment by aagonzales** [comment]
@joshblack I honestly have no clue what the context is here. This is beyond my technical knowledge. Maybe @marijohannessen or @tw15egan knows what Brian was talking about.

**Comment by aagonzales** [comment]
Or since this is in the public github maybe @hellobrian would be nice enough to give some context.

**Comment by hellobrian** [comment]
Hey! basically, this issue is about automating the build process for any SVG icons contributed to this repo. In other words, I wanted a way for Travis CI to execute the `npm run build` script and commit those built files to this repo automatically.

I ask contributors to either make a pull request, adding any new icons to the `src` directory (or I add it for them). Once merged into `master`, I run the build script (`npm run build`) to optimize the SVG file and then I make a new commit, which triggers all the npm publishing stuff via semantic-release.

I wasn't able to figure out how to do this properly when I was working on this repo, so that's the origin story of this issue. Let me know if that makes sense, and I'm happy to answer any other questions y'all may have.

**Comment by joshblack** [comment]
@hellobrian thanks for responding! 😄 

Do the build artifacts need to be checked into source control, or do they just need to be published with the package itself?

**Comment by hellobrian** [comment]
@joshblack Correct, I don't think the build artifacts (everything in `dist`) needs to be checked into source control; the build artifacts just need to be published with the package itself.
