### ISSUE TITLE
Contribution: Build

### ISSUE THREAD

**Issue by emily827** [carbon-design-system/carbon-icons#82]
The name of the icon is "build". It's going to be used when building something. The following .zip has the svg and an image of what it looks like.
[build.zip](https://github.com/IBM/carbon-icons/files/2412632/build.zip)

**Comment by asudoh** [comment]
Thank you for bringing this up @emily827! Let's see if how many other Carbon users want this icon, and if our (or brand) designers agrees that the icon fits well in Carbon ecosystem. Meanwhile, you can use your custom icon in `carbon-components-react`'s `<Icon>` component, by using a JSON data from SVG (XML) with a [conversion](https://github.com/IBM/carbon-icons/blob/v7.0.0/gulp-tasks/shared/formatJS.js), as [`<Icon>`'s `icon` prop](https://github.com/IBM/carbon-components-react/blob/v6.32.4/src/components/Icon/Icon.js#L172-L177). Data format examples can be found at https://unpkg.com/carbon-icons@7.0.0/dist/carbon-icons.js. Thanks!

**Comment by conradennis** [comment]
a version of this icon that is compatible with the new IBM Design Language is available here: https://next.carbondesignsystem.com/guidelines/iconography/library in the sketch kit or as individual SVGs from the icon library

look for the "development" icon

**Comment by mjabbink** [comment]
Close
